jobs:
    main:
        image: golang
        environment:
            GOPATH: /sd/workspace
            HEROKU_APP: screwdriver-demo
            HEROKU_APP_PR: screwdriver-demo-pr
            HEROKU_FINGERPRINT: 8b:48:5e:67:0e:c9:16:47:32:f2:87:0c:1f:c8:60:ad
        steps:
            - get: go get -t ./...
            - vet: go vet ./...
            - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
            - unit-test: go test ./...
            - build: go build -o randomer
            - functional-test: "PORT=8080 ./randomer & curl localhost:8080"
            - deploy: . ./ci/deploy.sh
            - ui-test: . ./ci/saucelabs.sh
        secrets:
            - HEROKU_SSH
            - SAUCE_KEY
            - SAUCE_USER
